spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:mysql://localhost:3306/sendmaildb
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  open-in-view: false



    # Data source postgressql
        #  datasource:
        #    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
        #    username: ${POSTGRES_SQL_USERNAME}
        #    password: ${POSTGRES_SQL_PASSWORD}

        #    jpa:
        #      generate-ddl: true
        #      show-sql: true
        #      hibernate:
        #        ddl-auto: update
        #      properties:
        #        hibernate:
        #          jdbc:
        #            time_zone: UTC
        #          globally_quoted_identifiers: true
        #          dialect: org.hibernate.dialect.PostgreSQLDialect
      #          format_sql: true
      # Data source postgressql


  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
          mime:
            charset: UTF
          smtp:
            writetimeout: 10000
            connectiontimeout: 10000
            timeout: 10000
            auth: true
            starttls:
              enable: true
              required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

  logo-ldcc: src/main/resources/static/logo_ldcc.png

server:
  port: ${SERVER_PORT:8080}
